name: Build and Publish Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t sjuprojekt .

      - name: Run test script inside container
        run: |
          docker run --rm sjuprojekt python /home/vscode/workspace/test.py

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag sjuprojekt ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
          docker tag sjuprojekt ${{ env.REGISTRY }}/${{ github.repository }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
